name: Deploy Proyecto
on: [push, workflow_dispatch]
jobs:
  prueba:
    runs-on: ubuntu-latest
    steps:
      - name: Descarga Codigo del Repositorio
        uses: actions/checkout@v3
      - name: Instalar NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar Dependecias
        run: npm ci
      - name: Ejecutar pruebas
        run: npm test
  despliegue:
    needs: prueba
    runs-on: ubuntu-latest
    steps:
      - name: Descarga Codigo del Repositorio
        uses: actions/checkout@v3
      - name: Instalar NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Instalar Dependecias
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Deploy
        run: echo "Deploying..."