name: Prueba Proyecto
on: push
jobs:
    prueba:
        runs-on: ubuntu-latest
        steps:
            - name: Descarga Codigo del Repositorio
                uses:
                    actions/checkout
            - name:
                Instalar NodeJS
                    uses: actions/setup-node@v3
                    with:
                        node-version: '18'
            - name: Instalar Dependecias
                run: npm ci
            - name: Ejecutar pruebas
                    run: npm test
